.TH "OXIM-SETUP" "1" "2008-11-26" "" ""
.SH "NAME"
oxim\-setup \- The OXIM Setup Environment
.SH "SYNOPSIS"
.B oxim\-setup
[\fI\-h\fR] [ \fIgambas\fR | \fIphp\fR | \fIgtk\fR | \fIqt3\fR ]
.br 
.SH "DESCRIPTION"
.I OXIM\-SETUP
is a oxim setup environment. You can install many kinds of input\-key from mirrors\-site in internet.
Oxim\-setup compatible with and containing many improvements over
.I GNU
.I OXIM
, writeen by FireFly of the Free Software Foundation.
.PP 
.I Oxim\-setup 
include more than three development environments. 
[
.I gambas php gtk qt3
] Your system will auto select the suitable from these environments.
If any one environment crash down, another one will run.
.BR 
You can easy change oxim.conf by using GUI oxim\-setup. 
By the tool, you can easy change the 
.I default selection
,
.I preset key
,
.I circular round
,I AutoFullUp for paste
... and more settings.
.BR 
You can change the phrase for your hotkey.
( 
.I ALT+Shift+KEYs
 )
.BR 
.SH "MORE INFORMATION"
For more information about \fIOxim\-Setup\fP, see the 
.I Ossii Page
(mentioned above),
look in the files $HOME/.oxim/,
or point your Web browser at 
.PP 
http://www.ossii.com.tw/
.PP 
for up\-to\-the\-minute information about \fIOxim\-Setup\fP.
.PP 
The lastest version of \fIOxim\-Setup\fP can be downloaded by using YUM or 
visit ftp.isu.edu.tw
.PP 
or from a mirror site near you. Mirror sites are listed in the file,
etc/FTP in the Ossii distribution or see the Web site for an up\-to\-date
list of mirror sites.
